name: Product Availability Checker

on:
  schedule:
     # Every day at 9am
      - cron: "0 9 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  check-product:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run product checker
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
          SMTP_TO: ${{ secrets.SMTP_TO }}
        run: |
          python main.py